language: java
#sudo: required

services:
  - docker

jdk:
# - oraclejdk8
  - openjdk6


before_install:
  - docker pull wnameless/oracle-xe-11g:14.04.4
  - DOCKER_ORACLE=$(docker run -d -p 49161:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g)
  - echo "Wait to allow Oracle to be initialized"
  - sleep 160
  - docker exec -i $DOCKER_ORACLE bash -c '/u01/app/oracle/product/11.2.0/xe/bin/lsnrctl stop'
  - docker exec -i $DOCKER_ORACLE bash -c '/u01/app/oracle/product/11.2.0/xe/bin/lsnrctl start'


script: "mvn verify"
